// Api01: generated by mimicplus from captured traffic of 127.0.0.1 (spec v4).
// Standalone: no dependencies. Type-checks with `tsc --strict`. Do not edit by hand; regenerate.
// Endpoints: 11 methods.
/* eslint-disable */
// ---- mimicplus TypeScript runtime (MIT; derived from mimicplus) -----------------------------
// Zero dependencies: needs only the WHATWG fetch API (Node >= 18, Deno, Bun, browsers).

export type QueryValue = string | number | boolean | null | undefined;
export type Query = Array<[string, QueryValue]>;
export type Json = unknown;

export interface RequestOptions {
  query?: Query;
  json?: unknown;
  form?: Record<string, unknown>;
  /** multipart/form-data fields; Blob values are sent as files */
  multipart?: Record<string, unknown>;
  body?: string;
  headers?: Record<string, string>;
  /** read-only: retried on 429/5xx/network errors */
  safe?: boolean;
  /** idempotent write: retried like a safe request */
  idempotent?: boolean;
  /** skip the learned auth-refresh / CSRF machinery (used internally) */
  bare?: boolean;
}

export interface RawResponse {
  status: number;
  headers: Headers;
  data: unknown;
  url: string;
}

export interface RequestInfo {
  method: string;
  url: string;
  status: number;
  ms: number;
  attempt: number;
}

export interface ClientOptions {
  baseUrl?: string;
  /** API token; formatted per the learned auth scheme (e.g. "Bearer {token}") */
  token?: string;
  headers?: Record<string, string>;
  /** initial cookie jar (name -> value), e.g. a saved session */
  cookies?: Record<string, string>;
  retries?: number;
  timeoutMs?: number;
  /** minimum delay between requests (politeness), default 0 */
  minIntervalMs?: number;
  fetch?: typeof fetch;
  userAgent?: string;
  /** observability hook, called after every HTTP attempt */
  onRequest?: (info: RequestInfo) => void;
}

export interface AuthFlowMeta {
  token_path: string;
  token_in: "header" | "query";
  token_name: string;
  token_format: string;
  expires_in_path: string | null;
  refresh_token_path: string | null;
}

export interface CsrfMeta {
  header: string;
  source: "cookie" | "body" | "header" | "html";
  name: string;
  method: string;
  path: string | null;
}

export interface SessionMeta {
  cookies: string[];
  csrf: CsrfMeta | null;
}

export interface PaginationMeta {
  style: "page" | "offset" | "cursor" | "next";
  param?: string;
  start?: number;
  size_param?: string | null;
  cursor_path?: string;
  next_path?: string;
  total_path?: string | null;
  items_path?: string | null;
}

export interface PageOptions {
  maxPages?: number;
  maxItems?: number;
}

export interface SseEvent {
  event: string;
  id: string | null;
  retry: number | null;
  data: unknown;
}

export class ApiError extends Error {
  readonly status: number;
  readonly body: unknown;
  readonly url: string;
  constructor(status: number, body: unknown, url: string) {
    const snippet = typeof body === "string" ? body.slice(0, 200) : JSON.stringify(body)?.slice(0, 200);
    super(`HTTP ${status} for ${url}: ${snippet ?? ""}`);
    this.name = "ApiError";
    this.status = status;
    this.body = body;
    this.url = url;
  }
}

const SAFE_METHODS = new Set(["GET", "HEAD", "OPTIONS"]);

export function getIn(obj: unknown, path: string | null | undefined): unknown {
  if (!path) return obj;
  let cur: unknown = obj;
  for (const k of path.split(".")) {
    if (cur === null || typeof cur !== "object") return undefined;
    cur = Array.isArray(cur) && /^\d+$/.test(k) ? cur[Number(k)] : (cur as Record<string, unknown>)[k];
  }
  return cur;
}

export function setPath(obj: Record<string, unknown>, path: string[], value: unknown): void {
  let cur: Record<string, unknown> = obj;
  for (const k of path.slice(0, -1)) {
    const next = cur[k];
    if (next === null || typeof next !== "object" || Array.isArray(next)) cur[k] = {};
    cur = cur[k] as Record<string, unknown>;
  }
  const last = path[path.length - 1];
  if (last !== undefined) cur[last] = value;
}

/** `[name, value, expired]` of one Set-Cookie header value. */
export function parseSetCookie(header: string): [string, string, boolean] | null {
  const [first, ...attrs] = header.split(";");
  const eq = (first ?? "").indexOf("=");
  if (eq <= 0) return null;
  const name = (first ?? "").slice(0, eq).trim();
  const value = (first ?? "").slice(eq + 1).trim().replace(/^"|"$/g, "");
  let expired = value === "";
  for (const a of attrs) {
    const [k, v = ""] = a.trim().split("=", 2) as [string, string?];
    if (k.toLowerCase() === "max-age" && Number(v) <= 0) expired = true;
    if (k.toLowerCase() === "expires" && Date.parse(v) < Date.now()) expired = true;
  }
  return [name, value, expired];
}

/** Dispatch text/event-stream lines into events (data JSON-decoded when it parses). */
export function* parseSseLines(lines: Iterable<string>): Generator<SseEvent> {
  let ev: { event?: string; id?: string; retry?: number } = {};
  let data: string[] = [];
  const flush = (): SseEvent | null => {
    if (!data.length && !ev.event && !ev.id) return null;
    const text = data.join("\n");
    let value: unknown = text;
    try {
      value = text ? JSON.parse(text) : null;
    } catch {
      value = text;
    }
    const out: SseEvent = { event: ev.event ?? "message", id: ev.id ?? null, retry: ev.retry ?? null, data: value };
    ev = {};
    data = [];
    return out;
  };
  for (const raw of [...lines, ""]) {
    const line = raw.replace(/\r$/, "");
    if (line === "") {
      const e = flush();
      if (e) yield e;
      continue;
    }
    if (line.startsWith(":")) continue;
    const i = line.indexOf(":");
    const field = i < 0 ? line : line.slice(0, i);
    let value = i < 0 ? "" : line.slice(i + 1);
    if (value.startsWith(" ")) value = value.slice(1);
    if (field === "data") data.push(value);
    else if (field === "event") ev.event = value;
    else if (field === "id") ev.id = value;
    else if (field === "retry" && /^\d+$/.test(value)) ev.retry = Number(value);
  }
}

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));

export class MimicClient {
  static BASE_URL = "";
  static DEFAULT_HEADERS: Record<string, string> = {};
  static AUTH_HEADERS: string[] = [];
  static AUTH_FLOW: AuthFlowMeta | null = null;
  static SESSION: SessionMeta | null = null;
  static USER_AGENT = "mimicplus-ts";
  /** true when the generated client learned a token-refresh endpoint */
  static CAN_REFRESH = false;

  baseUrl: string;
  headers: Record<string, string>;
  cookies: Record<string, string>;
  authQuery: Array<[string, string]> = [];
  csrf: string | null = null;
  refreshToken: string | null = null;
  tokenExpiresAt: number | null = null;
  retries: number;
  timeoutMs: number;
  minIntervalMs: number;
  lastStatus = 0;
  lastHeaders: Headers | null = null;
  protected fetchImpl: typeof fetch;
  protected onRequest: ((info: RequestInfo) => void) | undefined;
  private lastAt = 0;
  private busy = false;
  private refreshing = false;

  constructor(opts: ClientOptions = {}) {
    const meta = this.meta();
    this.baseUrl = (opts.baseUrl ?? meta.BASE_URL).replace(/\/$/, "");
    this.headers = { "user-agent": opts.userAgent ?? meta.USER_AGENT, ...meta.DEFAULT_HEADERS, ...(opts.headers ?? {}) };
    this.cookies = { ...(opts.cookies ?? {}) };
    this.retries = opts.retries ?? 3;
    this.timeoutMs = opts.timeoutMs ?? 30000;
    this.minIntervalMs = opts.minIntervalMs ?? 0;
    this.fetchImpl = opts.fetch ?? globalThis.fetch.bind(globalThis);
    this.onRequest = opts.onRequest;
    if (opts.token) this.setToken(opts.token);
  }

  protected meta(): typeof MimicClient {
    return this.constructor as typeof MimicClient;
  }

  /** Install an API token the learned way (header format or query parameter). */
  setToken(token: string): void {
    const flow = this.meta().AUTH_FLOW;
    if (flow) {
      const v = flow.token_format.replace("{token}", token);
      if (flow.token_in === "query") this.authQuery = [[flow.token_name, v]];
      else this.headers[flow.token_name] = v;
      return;
    }
    const h = this.meta().AUTH_HEADERS[0] ?? "authorization";
    this.headers[h] = h === "authorization" && !token.includes(" ") ? `Bearer ${token}` : token;
  }

  /** Apply a login/refresh response: token, refresh token and expiry from the learned paths. */
  protected applyAuth(resp: unknown): void {
    const flow = this.meta().AUTH_FLOW;
    if (!flow) return;
    const tok = getIn(resp, flow.token_path);
    if (typeof tok !== "string" || !tok) throw new ApiError(this.lastStatus, resp, "auth: no token in response");
    this.setToken(tok);
    const rt = flow.refresh_token_path ? getIn(resp, flow.refresh_token_path) : undefined;
    if (typeof rt === "string" && rt) this.refreshToken = rt;
    const exp = flow.expires_in_path ? getIn(resp, flow.expires_in_path) : undefined;
    this.tokenExpiresAt = typeof exp === "number" ? Date.now() + exp * 1000 : null;
  }

  /** Overridden by generated clients that learned a refresh endpoint. */
  protected async refreshCall(_refreshToken: string): Promise<unknown> {
    return undefined;
  }

  /** Exchange the refresh token for a new access token (single-flight); false if impossible. */
  async refreshAuth(): Promise<boolean> {
    if (!this.canRefresh() || this.refreshToken === null) return false;
    this.refreshing = true;
    try {
      this.applyAuth(await this.refreshCall(this.refreshToken));
      return true;
    } catch {
      return false;
    } finally {
      this.refreshing = false;
    }
  }

  protected canRefresh(): boolean {
    return this.refreshToken !== null && this.meta().CAN_REFRESH && !this.refreshing;
  }

  /** (Re)load the anti-CSRF token the learned way. */
  async fetchCsrf(): Promise<string | null> {
    const cfg = this.meta().SESSION?.csrf;
    if (!cfg) return null;
    if (cfg.source === "cookie") return (this.csrf = this.cookies[cfg.name] ?? null);
    const r = await this.send(cfg.method, cfg.path ?? "/", { safe: true, bare: true });
    if (cfg.source === "body") {
      const v = getIn(r.data, cfg.name);
      this.csrf = typeof v === "string" ? v : null;
    } else if (cfg.source === "header") {
      this.csrf = r.headers.get(cfg.name);
    } else {
      const html = typeof r.data === "string" ? r.data : "";
      const n = cfg.name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const m =
        new RegExp(`<meta[^>]*name=["']${n}["'][^>]*content=["']([^"']+)["']`, "i").exec(html) ??
        new RegExp(`<input[^>]*name=["']${n}["'][^>]*value=["']([^"']+)["']`, "i").exec(html);
      this.csrf = m?.[1] ?? null;
    }
    return this.csrf;
  }

  /** The decoded response body; throws ApiError on HTTP >= 400. */
  async request<T = unknown>(method: string, path: string, opts: RequestOptions = {}): Promise<T> {
    return (await this.send(method, path, opts)).data as T;
  }

  url(path: string, query: Query = []): string {
    const u = new URL(/^https?:\/\//.test(path) ? path : this.baseUrl + path);
    for (const [k, v] of [...query, ...this.authQuery]) {
      if (v !== undefined && v !== null) u.searchParams.append(k, String(v));
    }
    return u.toString();
  }

  async send(method: string, path: string, opts: RequestOptions = {}): Promise<RawResponse> {
    const unsafe = !SAFE_METHODS.has(method.toUpperCase());
    const csrfCfg = this.meta().SESSION?.csrf ?? null;
    if (!opts.bare && unsafe && csrfCfg && (!this.csrf || csrfCfg.source === "cookie") && !this.busy) {
      this.busy = true;
      try {
        await this.fetchCsrf();
      } finally {
        this.busy = false;
      }
    }
    if (!opts.bare && this.tokenExpiresAt !== null && Date.now() > this.tokenExpiresAt - 5000 && this.canRefresh()) {
      await this.refreshAuth();
    }
    const retryable = opts.safe === true || opts.idempotent === true || !unsafe;
    let refreshed = !!opts.bare;
    let csrfRetried = !!opts.bare;
    for (let attempt = 0; ; attempt++) {
      const url = this.url(path, opts.query);
      const headers: Record<string, string> = { ...this.headers, ...(opts.headers ?? {}) };
      const jar = Object.entries(this.cookies);
      if (jar.length) headers["cookie"] = jar.map(([k, v]) => `${k}=${v}`).join("; ");
      if (unsafe && csrfCfg && this.csrf) headers[csrfCfg.header] = this.csrf;
      let body: string | FormData | undefined;
      if (opts.json !== undefined) {
        body = JSON.stringify(opts.json);
        headers["content-type"] ??= "application/json";
      } else if (opts.form) {
        const f = new URLSearchParams();
        for (const [k, v] of Object.entries(opts.form)) if (v !== undefined && v !== null) f.append(k, String(v));
        body = f.toString();
        headers["content-type"] ??= "application/x-www-form-urlencoded";
      } else if (opts.multipart) {
        const f = new FormData();
        for (const [k, v] of Object.entries(opts.multipart)) {
          if (v instanceof Blob) f.append(k, v, k);
          else if (v !== undefined && v !== null) f.append(k, String(v));
        }
        body = f;
      } else if (opts.body !== undefined) {
        body = opts.body;
      }
      const wait = this.lastAt + this.minIntervalMs - Date.now();
      if (wait > 0) await sleep(wait);
      this.lastAt = Date.now();
      const t0 = Date.now();
      let res: Response;
      try {
        res = await this.fetchImpl(url, {
          method,
          headers,
          body,
          redirect: "follow",
          signal: AbortSignal.timeout(this.timeoutMs),
        });
      } catch (err) {
        if (retryable && attempt < this.retries) {
          await sleep(this.backoff(attempt, null));
          continue;
        }
        throw err;
      }
      this.absorbCookies(res.headers);
      const data = await this.decode(res);
      this.lastStatus = res.status;
      this.lastHeaders = res.headers;
      this.onRequest?.({ method, url, status: res.status, ms: Date.now() - t0, attempt });
      if (res.status === 401 && !refreshed && this.canRefresh()) {
        refreshed = true;
        if (await this.refreshAuth()) continue;
      }
      if ((res.status === 403 || res.status === 419) && unsafe && csrfCfg && !csrfRetried) {
        csrfRetried = true;
        this.csrf = null;
        await this.fetchCsrf();
        continue;
      }
      if (retryable && (res.status === 429 || res.status >= 500) && attempt < this.retries) {
        await sleep(this.backoff(attempt, res.headers.get("retry-after")));
        continue;
      }
      if (res.status >= 400) throw new ApiError(res.status, data, url);
      return { status: res.status, headers: res.headers, data, url };
    }
  }

  protected backoff(attempt: number, retryAfter: string | null): number {
    const ra = retryAfter !== null ? Number(retryAfter) : NaN;
    if (Number.isFinite(ra)) return Math.min(ra * 1000, 60000);
    return Math.min(250 * 2 ** attempt, 8000) * (0.5 + Math.random() / 2);
  }

  protected absorbCookies(h: Headers): void {
    const withGetter = h as Headers & { getSetCookie?: () => string[] };
    const raw = withGetter.getSetCookie ? withGetter.getSetCookie() : h.get("set-cookie") ? [h.get("set-cookie") ?? ""] : [];
    for (const line of raw) {
      const c = parseSetCookie(line);
      if (!c) continue;
      if (c[2]) delete this.cookies[c[0]];
      else this.cookies[c[0]] = c[1];
    }
  }

  protected async decode(res: Response): Promise<unknown> {
    const text = await res.text();
    if (!text) return null;
    if ((res.headers.get("content-type") ?? "").includes("json") || /^[[{]/.test(text.trim())) {
      try {
        return JSON.parse(text);
      } catch {
        return text;
      }
    }
    return text;
  }

  /** Items of a response: the learned items path, or the response itself when it is a list. */
  static items(resp: unknown, itemsPath: string | null | undefined): unknown[] {
    const v = itemsPath ? getIn(resp, itemsPath) : resp;
    return Array.isArray(v) ? v : [];
  }

  /** Iterate items across pages with a learned recipe (page / offset / cursor / next-link). */
  async *paginate<T>(
    call: (over: Record<string, unknown>) => Promise<unknown>,
    recipe: PaginationMeta,
    over: Record<string, unknown> = {},
    opts: PageOptions = {},
  ): AsyncGenerator<T> {
    const maxPages = opts.maxPages ?? 10;
    let yielded = 0;
    let pos: unknown = recipe.param !== undefined && over[recipe.param] !== undefined ? over[recipe.param] : recipe.start;
    const seen = new Set<string>();
    let nextUrl: string | null = null;
    for (let page = 0; page < maxPages; page++) {
      const args = { ...over };
      if (recipe.param !== undefined && pos !== undefined && pos !== null) args[recipe.param] = pos;
      const resp: unknown = nextUrl ? await this.request("GET", nextUrl, { safe: true }) : await call(args);
      const items = MimicClient.items(resp, recipe.items_path);
      const fp = JSON.stringify(items);
      if (!items.length || seen.has(fp)) return;
      seen.add(fp);
      for (const it of items) {
        yield it as T;
        if (opts.maxItems !== undefined && ++yielded >= opts.maxItems) return;
      }
      const total = recipe.total_path ? getIn(resp, recipe.total_path) : undefined;
      if (recipe.style === "page") pos = Number(pos ?? 1) + 1;
      else if (recipe.style === "offset") pos = Number(pos ?? 0) + items.length;
      else if (recipe.style === "cursor") {
        pos = getIn(resp, recipe.cursor_path);
        if (pos === undefined || pos === null || pos === "") return;
      } else {
        const n = getIn(resp, recipe.next_path);
        if (typeof n !== "string" || !n) return;
        nextUrl = n;
      }
      if (typeof total === "number" && recipe.style === "offset" && Number(pos) >= total) return;
    }
  }

  /** Server-Sent Events: yields events as they arrive. */
  async *sse(path: string, query: Query = [], maxEvents?: number, event?: string): AsyncGenerator<SseEvent> {
    const headers: Record<string, string> = { ...this.headers, accept: "text/event-stream" };
    const jar = Object.entries(this.cookies);
    if (jar.length) headers["cookie"] = jar.map(([k, v]) => `${k}=${v}`).join("; ");
    const url = this.url(path, query);
    const res = await this.fetchImpl(url, { headers });
    if (res.status >= 400) throw new ApiError(res.status, await res.text(), url);
    if (!res.body) return;
    const reader = res.body.getReader();
    const dec = new TextDecoder();
    let buf = "";
    let n = 0;
    try {
      for (;;) {
        const { value, done } = await reader.read();
        buf += done ? "\n\n" : dec.decode(value, { stream: true });
        let cut: number;
        while ((cut = buf.search(/\r?\n\r?\n/)) >= 0) {
          const block = buf.slice(0, cut);
          buf = buf.slice(cut).replace(/^\r?\n\r?\n/, "");
          for (const ev of parseSseLines(block.split(/\r?\n/))) {
            if (event && ev.event !== event) continue;
            yield ev;
            if (maxEvents !== undefined && ++n >= maxEvents) return;
          }
        }
        if (done) return;
      }
    } finally {
      await reader.cancel().catch(() => undefined);
    }
  }
}
// ---- end mimicplus runtime ------------------------------------------------------------------

// ---- learned types ----

export interface LoginResponse {
  access_token: string;
  refresh_token: string;
  token_type: string;
  expires_in: number;
}

export interface GetMeResponse {
  id: number;
  username: string;
  email: string;
  plan: string;
}

export interface ListProductsResponseItemsItem {
  id: number;
  in_stock: boolean;
  name: string;
  price: number;
  tags: Array<string>;
}

export interface ListProductsResponse {
  items: Array<ListProductsResponseItemsItem>;
  next_page: number | null;
  page: number;
  per_page: number;
  total: number;
}

export interface CreateItemResponseItem {
  product_id: number;
  qty: number;
}

export interface CreateItemResponse {
  cart_size: number;
  item: CreateItemResponseItem;
}

export interface SearchProductsResponseDataSearchProductsNodesItem {
  id: string;
  name: string;
  price: number;
}

export interface SearchProductsResponseDataSearchProducts {
  nodes: Array<SearchProductsResponseDataSearchProductsNodesItem>;
  totalCount: number;
}

export interface SearchProductsResponseData {
  searchProducts: SearchProductsResponseDataSearchProducts;
}

export interface SearchProductsResponse {
  data: SearchProductsResponseData;
}

export interface GetOrderResponseDataOrder {
  id: string;
  status: string;
  total: number;
  items: Array<number>;
}

export interface GetOrderResponseData {
  order: GetOrderResponseDataOrder;
}

export interface GetOrderResponse {
  data: GetOrderResponseData;
}

export interface AddReviewResponseDataAddReview {
  id: string;
  rating: number;
  ok: boolean;
}

export interface AddReviewResponseData {
  addReview: AddReviewResponseDataAddReview;
}

export interface AddReviewResponse {
  data: AddReviewResponseData;
}

export interface LoginArgs {
  username: string;
  password: string;
  /** extra top-level body fields, sent as-is */
  extra?: Record<string, unknown>;
}

export interface ListProductsArgs {
  page?: number;
  perPage?: number;
}

export interface CreateItemArgs {
  productId?: number;
  qty?: number;
  /** extra top-level body fields, sent as-is */
  extra?: Record<string, unknown>;
}

export interface SearchProductsArgs {
  q?: string;
  first?: number;
  /** extra top-level body fields, sent as-is */
  extra?: Record<string, unknown>;
}

export interface GetOrderArgs {
  id?: string;
  /** extra top-level body fields, sent as-is */
  extra?: Record<string, unknown>;
}

export interface AddReviewArgs {
  productId?: string;
  rating?: number;
  text?: string;
  /** extra top-level body fields, sent as-is */
  extra?: Record<string, unknown>;
}

export interface RefreshArgs {
  refreshToken: string;
  /** extra top-level body fields, sent as-is */
  extra?: Record<string, unknown>;
}

export const ENDPOINTS = [{"name": "login", "method": "POST", "path": "/api/auth/login", "safe": false}, {"name": "get_me", "method": "GET", "path": "/api/me", "safe": true}, {"name": "list_products", "method": "GET", "path": "/api/products", "safe": true}, {"name": "get_product", "method": "GET", "path": "/api/products/{product_id}", "safe": true}, {"name": "create_item", "method": "POST", "path": "/api/cart/items", "safe": false}, {"name": "search_products", "method": "POST", "path": "/graphql", "safe": true}, {"name": "get_order", "method": "POST", "path": "/graphql", "safe": true}, {"name": "add_review", "method": "POST", "path": "/graphql", "safe": false}, {"name": "refresh", "method": "POST", "path": "/api/auth/refresh", "safe": false}] as const;

export class Api01 extends MimicClient {
  static override BASE_URL = "http://127.0.0.1:8765";
  static override DEFAULT_HEADERS: Record<string, string> = {"accept": "application/json"};
  static override AUTH_HEADERS: string[] = ["authorization"];
  static override AUTH_FLOW: AuthFlowMeta | null = {"token_path": "access_token", "token_in": "header", "token_name": "authorization", "token_format": "Bearer {token}", "expires_in_path": "expires_in", "refresh_token_path": "refresh_token"};
  static override CAN_REFRESH = true;

  /** POST /api/auth/login -> 200 (WRITES) */
  async login(args: LoginArgs): Promise<LoginResponse> {
    const body: Record<string, unknown> = {"username": "", "password": ""};
    if (args.username === undefined) delete body["username"];
    else setPath(body, ["username"], args.username);
    if (args.password === undefined) delete body["password"];
    else setPath(body, ["password"], args.password);
    Object.assign(body, args.extra ?? {});
    return this.request<LoginResponse>("POST", `/api/auth/login`, { json: body });
  }

  /** GET /api/me -> 200 (read-only) */
  async getMe(): Promise<GetMeResponse> {
    return this.request<GetMeResponse>("GET", `/api/me`, { safe: true });
  }

  /** GET /api/products -> 200 (read-only) */
  async listProducts(args: ListProductsArgs = {}): Promise<ListProductsResponse> {
    return this.request<ListProductsResponse>("GET", `/api/products`, { query: [["page", args.page ?? "1"], ["per_page", args.perPage ?? "2"]], safe: true });
  }

  /** Every item of listProducts() across pages (learned page pagination). */
  async *listProductsAll(args: ListProductsArgs = {}, opts: PageOptions = {}): AsyncGenerator<ListProductsResponseItemsItem> {
    yield* this.paginate<ListProductsResponseItemsItem>((o) => this.listProducts({ ...args, ...o } as ListProductsArgs), {"items_path": "items", "total_path": "total", "size_param": "perPage", "style": "page", "param": "page", "start": 1}, { ...args }, opts);
  }

  /** GET /api/products/{product_id} -> 200 (read-only) */
  async getProduct(productId: number): Promise<ListProductsResponseItemsItem> {
    return this.request<ListProductsResponseItemsItem>("GET", `/api/products/${encodeURIComponent(String(productId))}`, { safe: true });
  }

  /** POST /api/cart/items -> 201 (WRITES) */
  async createItem(args: CreateItemArgs = {}): Promise<CreateItemResponse> {
    const body: Record<string, unknown> = {"product_id": 104, "qty": 1};
    if (args.productId !== undefined) setPath(body, ["product_id"], args.productId);
    if (args.qty !== undefined) setPath(body, ["qty"], args.qty);
    Object.assign(body, args.extra ?? {});
    return this.request<CreateItemResponse>("POST", `/api/cart/items`, { json: body });
  }

  /** POST /graphql -> 200 (read-only) GraphQL query SearchProducts*/
  async searchProducts(args: SearchProductsArgs = {}): Promise<SearchProductsResponse> {
    const body: Record<string, unknown> = {"operationName": "SearchProducts", "query": "query SearchProducts($q: String!, $first: Int) { searchProducts(q: $q, first: $first) { totalCount nodes { id name price } } }", "variables": {"q": "lamp", "first": 5}};
    if (args.q !== undefined) setPath(body, ["variables", "q"], args.q);
    if (args.first !== undefined) setPath(body, ["variables", "first"], args.first);
    Object.assign(body, args.extra ?? {});
    return this.request<SearchProductsResponse>("POST", `/graphql`, { json: body, safe: true });
  }

  /** POST /graphql -> 200 (read-only) GraphQL query GetOrder*/
  async getOrder(args: GetOrderArgs = {}): Promise<GetOrderResponse> {
    const body: Record<string, unknown> = {"operationName": "GetOrder", "query": "query GetOrder($id: ID!) { order(id: $id) { id status total items } }", "variables": {"id": "o-1"}};
    if (args.id !== undefined) setPath(body, ["variables", "id"], args.id);
    Object.assign(body, args.extra ?? {});
    return this.request<GetOrderResponse>("POST", `/graphql`, { json: body, safe: true });
  }

  /** POST /graphql -> 200 (WRITES) GraphQL mutation AddReview*/
  async addReview(args: AddReviewArgs = {}): Promise<AddReviewResponse> {
    const body: Record<string, unknown> = {"operationName": "AddReview", "query": "mutation AddReview($productId: ID!, $rating: Int!, $text: String) { addReview(productId: $productId, rating: $rating, text: $text) { id rating ok } }", "variables": {"productId": "101", "rating": 5, "text": "great"}};
    if (args.productId !== undefined) setPath(body, ["variables", "productId"], args.productId);
    if (args.rating !== undefined) setPath(body, ["variables", "rating"], args.rating);
    if (args.text !== undefined) setPath(body, ["variables", "text"], args.text);
    Object.assign(body, args.extra ?? {});
    return this.request<AddReviewResponse>("POST", `/graphql`, { json: body });
  }

  /** POST /api/auth/refresh -> 200 (WRITES) */
  async refresh(args: RefreshArgs): Promise<LoginResponse> {
    const body: Record<string, unknown> = {"refresh_token": ""};
    if (args.refreshToken === undefined) delete body["refresh_token"];
    else setPath(body, ["refresh_token"], args.refreshToken);
    Object.assign(body, args.extra ?? {});
    return this.request<LoginResponse>("POST", `/api/auth/refresh`, { json: body });
  }

  /** Log in with the learned flow and keep the returned token (credentials are never stored). */
  async authenticate(args: LoginArgs): Promise<LoginResponse> {
    const r = await this.login(args);
    this.applyAuth(r);
    return r;
  }

  protected override async refreshCall(refreshToken: string): Promise<unknown> {
    return this.refresh({ refreshToken: refreshToken } as RefreshArgs);
  }
}

export default Api01;
